# Generated by Django 4.2.7 on 2024-01-25 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0004_alter_purcehase_history_isborrowd_ratings'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='isProduct_Stock',
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
    ]
