# Generated by Django 4.2.7 on 2024-02-12 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_alter_publisherinfo_soldbookcount'),
    ]

    operations = [
        migrations.AddField(
            model_name='publisherinfo',
            name='adminPermission',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
