# Generated by Django 4.2.7 on 2024-02-15 06:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_publisherinfo_adminpermission'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publisherinfo',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='publisherAccount', to='user.useraccount'),
        ),
    ]
